# Generated by Django 5.1.3 on 2024-11-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Echoverse", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="rating",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
