# Generated by Django 5.1.3 on 2024-11-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Echoverse", "0002_review_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(default=0),
        ),
    ]
