# Generated by Django 5.1.2 on 2024-11-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Echoverse', '0006_rename_text_comment_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
