# Generated by Django 5.1.3 on 2024-11-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Echoverse', '0011_post_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
