# Generated by Django 5.1.3 on 2024-11-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Echoverse', '0012_rename_content_comment_text_alter_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_profile_picture.png', upload_to='profile_pictures/'),
            preserve_default=False,
        ),
    ]
