# Generated by Django 5.1.3 on 2024-11-21 06:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Echoverse', '0018_category_blogpost_image_blogpost_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinteraction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='liked',
            field=models.BooleanField(default=True),
        ),
    ]
