# Generated by Django 5.1.3 on 2024-11-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Echoverse', '0019_userinteraction_created_at_alter_tag_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinteraction',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
