# Generated by Django 5.1.3 on 2024-11-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Echoverse', '0020_userinteraction_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinteraction',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
