# Generated by Django 5.1.3 on 2024-11-26 03:52

import Echoverse.models
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Echoverse", "0022_remove_comment_post_comment_blog_post_rating_review"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="blog_post",
            new_name="post",
        ),
        migrations.RenameField(
            model_name="rating",
            old_name="blog_post",
            new_name="post",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="blog_post",
            new_name="post",
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="review",
            name="rating",
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="post_images/",
                validators=[Echoverse.models.validate_image],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                upload_to="profile_pictures/",
                validators=[Echoverse.models.validate_image],
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userinteraction",
            name="liked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(
                fields=("post", "user"), name="unique_post_user_like"
            ),
        ),
    ]
